/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => InlineEncrypterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/Settings.ts
var import_obsidian = require("obsidian");

// src/Globals.ts
var State = { passwordGlobal: "", passwordRemember: false };
function saveStatePasswordGlobal(value) {
  State.passwordGlobal = value;
}
function saveStatePasswordRemember(value) {
  State.passwordRemember = value;
}

// src/Settings.ts
var DEFAULT_SETTINGS = {
  autoCopy: false,
  rememberPassword: false
};
var InlineEncrypterSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.icon = "lock";
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Auto copy secret to clipboard").setDesc("Copy secret to clipboard automatically").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoCopy).onChange(async (value) => {
        this.plugin.settings.autoCopy = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Remember password until session restarts").setDesc("Remember correct password until Obsidian session restarts").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.rememberPassword).onChange(async (value) => {
        this.plugin.settings.rememberPassword = value;
        if (value === false) {
          saveStatePasswordGlobal("");
        }
        saveStatePasswordRemember(value);
        await this.plugin.saveSettings();
        this.display();
      })
    );
  }
};

// src/ModalPassword.ts
var import_obsidian2 = require("obsidian");

// src/Constants.ts
var ENCRYPTED_CODE_PREFIX = "secret";
var ENCRYPTED_CODE_SVG = `<svg version="1.1" viewBox="0 0 95.25 15.875" xmlns="http://www.w3.org/2000/svg">
 <g transform="translate(-67.168 -52.917)">
   <g stroke-width=".22324" aria-label="SECRET" fill="currentColor">
   <path d="m95.294 68.262q-2.0574 0-3.2766-1.0668-1.2192-1.0858-1.2192-2.9718h1.8859q0 1.1049 0.70485 1.7336t1.905 0.62865q1.143 0 1.8098-0.62865 0.6858-0.6477 0.6858-1.7145 0-0.8001-0.43815-1.3906-0.43815-0.6096-1.2382-0.81915l-2.0574-0.55245q-1.3526-0.381-2.1526-1.3716-0.78105-1.0096-0.78105-2.3812 0-1.124 0.4953-1.9622 0.51435-0.85725 1.4287-1.3144 0.9144-0.47625 2.1146-0.47625 1.2192 0 2.1336 0.47625 0.93345 0.4572 1.4478 1.2954t0.51435 1.9431h-1.8669q0-0.9144-0.6096-1.4859-0.6096-0.5715-1.6002-0.5715t-1.6002 0.5715q-0.59055 0.5715-0.59055 1.4859 0 0.74295 0.40005 1.2573 0.40005 0.4953 1.124 0.70485l2.1146 0.5715q1.4288 0.381 2.2288 1.4668 0.8001 1.0668 0.8001 2.5527 0 1.2192-0.5334 2.1336-0.5334 0.89535-1.524 1.3906-0.97155 0.4953-2.286 0.4953z"/>
   <path d="m102.78 68.072v-13.906h8.0962v1.6954h-6.2293v4.1338h5.5626v1.6383h-5.5626v4.7434h6.2293v1.6954z"/>
   <path d="m118.23 68.262q-1.924 0-3.067-1.0668-1.124-1.0858-1.124-2.9718v-6.2294q0-1.8669 1.124-2.9337 1.143-1.0858 3.067-1.0858 1.905 0 3.029 1.0858 1.143 1.0858 1.143 2.9337h-1.886q0-1.124-0.6096-1.7336t-1.6764-0.6096q-1.0858 0-1.6954 0.6096t-0.6096 1.7336v6.2294q0 1.143 0.6096 1.7526t1.6954 0.6096q1.0668 0 1.6764-0.6096t0.6096-1.7526h1.886q0 1.8669-1.143 2.9528-1.124 1.0858-3.029 1.0858z"/>
   <path d="m125.49 68.072v-13.906h4.3053q1.2764 0 2.2288 0.51435 0.9525 0.4953 1.4859 1.4097 0.5334 0.89535 0.5334 2.1146 0 1.4097-0.7239 2.4194-0.70485 1.0096-1.886 1.4288l2.8004 6.0198h-2.0764l-2.648-5.8102h-2.1526v5.8102zm1.8669-7.4866h2.4384q1.0668 0 1.6764-0.6477 0.62865-0.6477 0.62865-1.7145 0-1.0858-0.62865-1.7336t-1.6764-0.6477h-2.4384z"/>
   <path d="m137.07 68.072v-13.906h8.0962v1.6954h-6.2294v4.1338h5.5626v1.6383h-5.5626v4.7434h6.2294v1.6954z"/>
   <path d="m151.43 68.072v-12.192h-3.7719v-1.7145h9.4107v1.7145h-3.7528v12.192z"/>
  </g>
   <g id="XMLID_509_" transform="matrix(.057518 0 0 .048106 70.113 52.917)" fill="currentColor">
   <path id="XMLID_510_" d="m65 330h200c8.284 0 15-6.716 15-15v-170c0-8.284-6.716-15-15-15h-15v-45c0-46.869-38.131-85-85-85s-85 38.131-85 85v45h-15c-8.284 0-15 6.716-15 15v170c0 8.284 6.716 15 15 15zm115-95.014v20.014c0 8.284-6.716 15-15 15s-15-6.716-15-15v-20.014c-6.068-4.565-10-11.824-10-19.986 0-13.785 11.215-25 25-25s25 11.215 25 25c0 8.162-3.932 15.421-10 19.986zm-70-149.99c0-30.327 24.673-55 55-55s55 24.673 55 55v45h-110z"/>
  </g>
 </g>
</svg>`;

// src/ModalPassword.ts
var ModalPassword = class extends import_obsidian2.Modal {
  constructor(app, textType) {
    super(app);
    this.password = State.passwordGlobal;
    this.input = "";
    this.isPassword = false;
    this.textType = textType;
  }
  onOpen() {
    if (State.passwordGlobal.length > 0 && State.passwordRemember && this.textType != 1 /* PreEncrypted */) {
      this.passwordOk();
    }
    const { contentEl } = this;
    let textArea;
    if (this.textType === 1 /* PreEncrypted */) {
      contentEl.createEl("h1", { text: "Enter password and text for encryption" });
    } else {
      contentEl.createEl("h1", { text: "Enter password" });
    }
    new import_obsidian2.Setting(contentEl).setName("Password").addText((text) => {
      text.inputEl.type = "password";
      if (State.passwordGlobal.length > 0 && State.passwordRemember) {
        text.inputEl.value = State.passwordGlobal;
      }
      text.inputEl.addEventListener("keypress", (event) => {
        if (event.key === "Enter") {
          this.passwordOk();
        }
      });
      text.onChange((value) => this.password = value);
    });
    new import_obsidian2.Setting(contentEl).setName("Show password").addToggle(
      (toggle) => toggle.setValue(false).onChange((value) => {
        const input = this.contentEl.querySelector("input");
        if (input) {
          input.type = value ? "text" : "password";
        }
      })
    );
    if (this.textType === 1 /* PreEncrypted */) {
      contentEl.classList.add("inline-encrypter-encrypt-text-modal");
      new import_obsidian2.Setting(contentEl).setName("Text to encrypt").addTextArea((cb) => {
        textArea = cb;
        cb.setValue(this.input);
        cb.inputEl.readOnly = false;
        cb.inputEl.cols = 30;
        cb.inputEl.rows = 8;
      });
    }
    new import_obsidian2.Setting(contentEl).addButton((btn) => btn.setButtonText("OK").setCta().onClick(() => {
      if (this.textType === 1 /* PreEncrypted */) {
        this.input = textArea.getValue();
      }
      this.passwordOk();
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  passwordOk() {
    this.isPassword = true;
    if (State.passwordRemember) {
      saveStatePasswordGlobal(this.password);
    }
    this.close();
  }
};

// src/CryptoFactory.ts
var CryptoFactory = class {
  constructor() {
    this.vectorSize = 16;
    this.saltSize = 16;
    this.iterations = 262144;
  }
  convertArrayToString(bytes) {
    let result = "";
    for (let i = 0; i < bytes.length; i++) {
      result += String.fromCharCode(bytes[i]);
    }
    return result;
  }
  convertStringToArray(str) {
    const result = [];
    for (let i = 0; i < str.length; i++) {
      result.push(str.charCodeAt(i));
    }
    return new Uint8Array(result);
  }
  async deriveKey(password, salt) {
    const utf8Encoder = new TextEncoder();
    const keyData = utf8Encoder.encode(password);
    const key = await crypto.subtle.importKey("raw", keyData, { name: "PBKDF2" }, false, ["deriveKey"]);
    const privateKey = await crypto.subtle.deriveKey(
      {
        name: "PBKDF2",
        hash: { name: "SHA-512" },
        salt: salt.slice().buffer,
        iterations: this.iterations
      },
      key,
      {
        name: "AES-GCM",
        length: 256
      },
      false,
      ["encrypt", "decrypt"]
    );
    return privateKey;
  }
  async encryptToBytes(text, password) {
    const salt = crypto.getRandomValues(new Uint8Array(this.saltSize));
    const key = await this.deriveKey(password, salt);
    const utf8Encoder = new TextEncoder();
    const textBytesToEncrypt = utf8Encoder.encode(text);
    const vector = crypto.getRandomValues(new Uint8Array(this.vectorSize));
    const encryptedBytes = new Uint8Array(
      await crypto.subtle.encrypt(
        {
          name: "AES-GCM",
          iv: vector
        },
        key,
        textBytesToEncrypt
      )
    );
    const finalBytes = new Uint8Array(vector.byteLength + salt.byteLength + encryptedBytes.byteLength);
    finalBytes.set(vector, 0);
    finalBytes.set(salt, vector.byteLength);
    finalBytes.set(encryptedBytes, vector.byteLength + salt.byteLength);
    return finalBytes;
  }
  async encryptToBase64(text, password) {
    const finalBytes = await this.encryptToBytes(text, password);
    const base64Text = btoa(this.convertArrayToString(finalBytes));
    return base64Text;
  }
  async decryptFromBytes(encryptedBytes, password) {
    try {
      let offset;
      let nextOffset;
      offset = 0;
      nextOffset = offset + this.vectorSize;
      const vector = encryptedBytes.slice(offset, nextOffset);
      offset = nextOffset;
      nextOffset = offset + this.saltSize;
      const salt = encryptedBytes.slice(offset, nextOffset);
      offset = nextOffset;
      nextOffset = void 0;
      const encryptedTextBytes = encryptedBytes.slice(offset);
      const key = await this.deriveKey(password, salt);
      const decryptedBytes = await crypto.subtle.decrypt(
        {
          name: "AES-GCM",
          iv: vector
        },
        key,
        encryptedTextBytes
      );
      const utf8Decoder = new TextDecoder();
      const decryptedText = utf8Decoder.decode(decryptedBytes);
      return decryptedText;
    } catch (e) {
      return null;
    }
  }
  async decryptFromBase64(base64Encoded, password) {
    try {
      const bytesToDecode = this.convertStringToArray(atob(base64Encoded));
      return await this.decryptFromBytes(bytesToDecode, password);
    } catch (e) {
      return null;
    }
  }
};

// src/UiHelper.ts
var import_obsidian4 = require("obsidian");

// src/ModalDecrypt.ts
var import_obsidian3 = require("obsidian");
var ModalDecrypt = class extends import_obsidian3.Modal {
  constructor(app, text = "", autoCopy) {
    super(app);
    this.text = text;
    this.autoCopy = autoCopy;
  }
  onOpen() {
    var _a;
    const { contentEl } = this;
    contentEl.empty();
    contentEl.classList.add("inline-encrypter-decrypt-modal");
    contentEl.createEl("h1", { text: "Decrypted secret" });
    let textArea;
    const textVal = new import_obsidian3.Setting(contentEl).addTextArea((cb) => {
      textArea = cb;
      cb.setValue(this.text);
      cb.inputEl.setSelectionRange(0, 0);
      cb.inputEl.readOnly = true;
      cb.inputEl.cols = 50;
      cb.inputEl.rows = 10;
      if (this.autoCopy == true) {
        navigator.clipboard.writeText(textArea.getValue());
        new import_obsidian3.Notice("Secret copied");
      }
    });
    (_a = textVal.settingEl.querySelector(".setting-item-info")) == null ? void 0 : _a.remove();
    const buttons = new import_obsidian3.Setting(contentEl);
    buttons.addButton((cb) => {
      cb.setButtonText("Copy to clipboard").onClick((evt) => {
        navigator.clipboard.writeText(textArea.getValue());
        new import_obsidian3.Notice("Secret copied");
      });
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/UiHelper.ts
var UiHelper = class {
  handleDecryptClick(app, plugin, event, input) {
    event.preventDefault();
    const copyOnly = !!event.ctrlKey;
    this.decryptFlow(app, plugin, input, copyOnly);
  }
  openContextMenuAt(app, plugin, pos, input) {
    const menu = new import_obsidian4.Menu();
    menu.addItem(
      (item) => item.setTitle("Decrypt").setIcon("lock-open").onClick(() => this.decryptFlow(app, plugin, input, false))
    );
    menu.addItem(
      (item) => item.setTitle("Decrypt and copy").setIcon("copy").onClick(() => this.decryptFlow(app, plugin, input, true))
    );
    menu.showAtPosition(pos);
  }
  openContextMenuAtEvent(app, plugin, ev, input) {
    const menu = new import_obsidian4.Menu();
    menu.addItem(
      (item) => item.setTitle("Decrypt").setIcon("lock-open").onClick(() => this.decryptFlow(app, plugin, input, false))
    );
    menu.addItem(
      (item) => item.setTitle("Decrypt and copy").setIcon("copy").onClick(() => this.decryptFlow(app, plugin, input, true))
    );
    menu.showAtMouseEvent(ev);
  }
  normalizeEncryptedInput(input) {
    return input.replace(ENCRYPTED_CODE_PREFIX, "").replace(/`/g, "").replace(/\s/g, "").replace(/\r?\n|\r/g, "");
  }
  async decryptFlow(app, plugin, input, copyOnly) {
    const cryptoFactory = new CryptoFactory();
    const passModal = new ModalPassword(app, 0 /* Inline */);
    passModal.onClose = async () => {
      if (!passModal.isPassword) return;
      const cleaned = this.normalizeEncryptedInput(input);
      const output = await cryptoFactory.decryptFromBase64(cleaned, passModal.password);
      if (output === null) {
        new import_obsidian4.Notice("\u274C Decryption failed!");
        saveStatePasswordGlobal("");
        return;
      }
      if (copyOnly) {
        try {
          await navigator.clipboard.writeText(output);
          new import_obsidian4.Notice("Secret copied");
        } catch (e) {
          new import_obsidian4.Notice("Failed to copy to clipboard");
        }
      } else {
        new ModalDecrypt(app, output, plugin.settings.autoCopy).open();
      }
    };
    passModal.open();
  }
  selectionAndRangeOverlap(selection, rangeFrom, rangeTo) {
    for (const range of selection.ranges) {
      if (range.from <= rangeTo && range.to >= rangeFrom) {
        return true;
      }
    }
    return false;
  }
};

// src/LivePreviewExtension.ts
var import_obsidian5 = require("obsidian");
var import_view2 = require("@codemirror/view");
var import_state = require("@codemirror/state");
var import_language = require("@codemirror/language");

// src/InlineWidget.ts
var import_view = require("@codemirror/view");
var InlineWidget = class extends import_view.WidgetType {
  constructor(app, plugin, value) {
    super();
    this.app = app;
    this.value = value;
    this.plugin = plugin;
  }
  toDOM(view) {
    const uiHelper = new UiHelper();
    const div = document.createElement("div");
    div.addClass("inline-encrypter-lp-code");
    const a = div.createEl("a", { cls: "inline-encrypter-code" });
    a.innerHTML = ENCRYPTED_CODE_SVG;
    a.addEventListener("click", (event) => {
      if (event.button !== 0 /* Left */) return;
      uiHelper.handleDecryptClick(this.app, this.plugin, event, this.value);
    });
    a.addEventListener("mouseup", (event) => {
      if (event.button !== 2 /* Right */) return;
      event.preventDefault();
      event.stopPropagation();
      const pos = { x: event.clientX, y: event.clientY };
      setTimeout(() => uiHelper.openContextMenuAt(this.app, this.plugin, pos, this.value), 0);
    });
    a.addEventListener("contextmenu", (event) => {
      event.preventDefault();
      event.stopPropagation();
      event.stopImmediatePropagation();
      if (event.ctrlKey) {
        const clickEvent = new MouseEvent("click", {
          ctrlKey: true,
          bubbles: true,
          cancelable: true,
          view: window
        });
        a.dispatchEvent(clickEvent);
      }
    });
    return div;
  }
};

// src/LivePreviewExtension.ts
var livePreviewExtension = (app, plugin) => import_view2.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.decorations = this.buildDecorations(view);
    }
    update(update) {
      if (!update.state.field(import_obsidian5.editorLivePreviewField)) {
        this.decorations = import_view2.Decoration.none;
        return;
      }
      if (update.docChanged || update.viewportChanged || update.selectionSet) {
        this.decorations = this.buildDecorations(update.view);
      }
    }
    destroy() {
    }
    buildDecorations(view) {
      if (!view.state.field(import_obsidian5.editorLivePreviewField)) return import_view2.Decoration.none;
      const uiHelper = new UiHelper();
      const builder = new import_state.RangeSetBuilder();
      const selection = view.state.selection;
      for (const { from, to } of view.visibleRanges) {
        (0, import_language.syntaxTree)(view.state).iterate({
          from,
          to,
          enter(node) {
            if (node.type.name.startsWith("inline-code")) {
              const value = view.state.doc.sliceString(node.from, node.to);
              const isEncrypted = value.startsWith(ENCRYPTED_CODE_PREFIX + " ");
              if (isEncrypted) {
                if (!uiHelper.selectionAndRangeOverlap(selection, node.from - 1, node.to + 1)) {
                  builder.add(
                    node.from,
                    node.to,
                    import_view2.Decoration.replace({
                      widget: new InlineWidget(app, plugin, value)
                    })
                  );
                }
              }
            }
          }
        });
      }
      return builder.finish();
    }
  },
  {
    decorations: (instance) => instance.decorations
  }
);

// src/main.ts
var InlineEncrypterPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.cryptoFactory = new CryptoFactory();
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new InlineEncrypterSettingTab(this.app, this));
    saveStatePasswordRemember(this.settings.rememberPassword);
    this.registerMarkdownPostProcessor((el, ctx) => this.processEncryptedInlineCodeBlockProcessor(el, ctx));
    this.registerMarkdownCodeBlockProcessor(ENCRYPTED_CODE_PREFIX, (source, el, ctx) => this.processEncryptedCodeBlockProcessor(source, el, ctx));
    this.registerEditorExtension(livePreviewExtension(this.app, this));
    this.addCommand({
      id: "encrypt",
      name: "Encrypt selected text",
      icon: "lock",
      editorCallback: (editor, _view) => this.processInlineEncryptCommand(editor, 0 /* Inline */, 0 /* Inline */)
    });
    this.addCommand({
      id: "encrypt-code",
      name: "Encrypt selected text as code block",
      icon: "lock",
      editorCallback: (editor, _view) => this.processInlineEncryptCommand(editor, 1 /* Common */, 0 /* Inline */)
    });
    this.addCommand({
      id: "encrypt-pre",
      name: "Insert pre-encrypted text",
      icon: "lock",
      editorCallback: (editor, _view) => this.processInlineEncryptCommand(editor, 0 /* Inline */, 1 /* PreEncrypted */)
    });
    this.addCommand({
      id: "decrypt",
      name: "Decrypt selected text",
      icon: "lock",
      editorCallback: (editor, _view) => this.processInlineDecryptCommand(editor)
    });
    console.log("Inline Encrypter plugin loaded");
  }
  onunload() {
    console.log("Inline Encrypter plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async processInlineEncryptCommand(editor, codeBlockType, textType) {
    if (textType === 0 /* Inline */) {
      if (editor.somethingSelected()) {
        const input = editor.getSelection();
        const passModal = new ModalPassword(this.app, textType);
        passModal.onClose = async () => {
          if (!passModal.isPassword) {
            return;
          }
          const output = await this.cryptoFactory.encryptToBase64(input, passModal.password);
          if (codeBlockType === 0 /* Inline */) {
            editor.replaceSelection("`" + ENCRYPTED_CODE_PREFIX + " " + output + "`");
          }
          if (codeBlockType === 1 /* Common */) {
            editor.replaceSelection("```" + ENCRYPTED_CODE_PREFIX + "\n" + output + "\n```");
          }
          if (passModal.password.length === 0) {
            new import_obsidian6.Notice("\u26A0\uFE0F Password is empty");
          }
          new import_obsidian6.Notice("\u2705 Text encrypted");
        };
        passModal.open();
      } else {
        new import_obsidian6.Notice("\u274C No selected text for encryption");
      }
    }
    if (textType === 1 /* PreEncrypted */) {
      const passModal = new ModalPassword(this.app, textType);
      passModal.onClose = async () => {
        const input = passModal.input;
        if (input.length > 0) {
          if (!passModal.isPassword) {
            return;
          }
          const output = await this.cryptoFactory.encryptToBase64(input, passModal.password);
          if (codeBlockType === 0 /* Inline */) {
            editor.replaceSelection("`" + ENCRYPTED_CODE_PREFIX + " " + output + "`");
          }
          if (codeBlockType === 1 /* Common */) {
            editor.replaceSelection("```" + ENCRYPTED_CODE_PREFIX + "\n" + output + "\n```");
          }
          if (passModal.password.length === 0) {
            new import_obsidian6.Notice("\u26A0\uFE0F Password is empty");
          }
          new import_obsidian6.Notice("\u2705 Text encrypted");
        } else {
          new import_obsidian6.Notice("\u274C No text for encryption");
        }
      };
      passModal.open();
    }
  }
  async processInlineDecryptCommand(editor) {
    let selected = editor.getSelection();
    if (!selected || selected.length === 0) {
      const block = this.findEncryptedBlockAtCursor(editor);
      if (block) {
        editor.setSelection(block.from, block.to);
      } else {
        new import_obsidian6.Notice("\u274C Encrypted block not found");
        return;
      }
    }
    if (editor.somethingSelected()) {
      let input = editor.getSelection();
      const passModal = new ModalPassword(this.app, 0 /* Inline */);
      passModal.onClose = async () => {
        if (!passModal.isPassword) {
          return;
        }
        input = input.replace(ENCRYPTED_CODE_PREFIX, "").replace(/`/g, "").replace(/\s/g, "").replace(/\r?\n|\r/g, "");
        const output = await this.cryptoFactory.decryptFromBase64(input, passModal.password);
        if (output === null) {
          new import_obsidian6.Notice("\u274C Decryption failed!");
          saveStatePasswordGlobal("");
          return;
        } else {
          editor.replaceSelection(output);
          new import_obsidian6.Notice("\u2705 Text decrypted");
        }
      };
      passModal.open();
    } else {
      new import_obsidian6.Notice("\u274C No selected text for decryption");
      return;
    }
  }
  processEncryptedInlineCodeBlockProcessor(el, ctx) {
    const uiHelper = new UiHelper();
    const codes = el.querySelectorAll("code");
    if (!codes || codes.length === 0) return;
    codes.forEach((codeEl) => {
      var _a;
      if (((_a = codeEl.parentElement) == null ? void 0 : _a.tagName) === "PRE") return;
      const raw = (codeEl.textContent || "").trim();
      if (!raw || !raw.startsWith(ENCRYPTED_CODE_PREFIX + " ")) return;
      codeEl.innerText = "";
      const btn = codeEl.createEl("a", { cls: "inline-encrypter-code" });
      btn.innerHTML = ENCRYPTED_CODE_SVG;
      btn.dataset.secret = raw;
      btn.addEventListener("click", (ev) => {
        if (ev.button !== 0 /* Left */) return;
        ev.preventDefault();
        uiHelper.handleDecryptClick(this.app, this, ev, btn.dataset.secret || "");
      });
      btn.addEventListener("contextmenu", (ev) => {
        var _a2, _b;
        if (ev.ctrlKey) {
          ev.preventDefault();
          ev.stopPropagation();
          (_a2 = ev.stopImmediatePropagation) == null ? void 0 : _a2.call(ev);
          uiHelper.handleDecryptClick(this.app, this, ev, btn.dataset.secret || "");
          return;
        }
        ev.preventDefault();
        ev.stopPropagation();
        (_b = ev.stopImmediatePropagation) == null ? void 0 : _b.call(ev);
        setTimeout(() => uiHelper.openContextMenuAtEvent(this.app, this, ev, btn.dataset.secret || ""), 0);
      }, { capture: true });
    });
  }
  processEncryptedCodeBlockProcessor(source, el, ctx) {
    const uiHelper = new UiHelper();
    const btn = el.createEl("a", { cls: "inline-encrypter-code" });
    btn.innerHTML = ENCRYPTED_CODE_SVG;
    btn.dataset.secret = (source || "").trim();
    btn.addEventListener("click", (ev) => {
      if (ev.button !== 0 /* Left */) return;
      ev.preventDefault();
      uiHelper.handleDecryptClick(this.app, this, ev, btn.dataset.secret || "");
    });
    btn.addEventListener("contextmenu", (ev) => {
      var _a, _b;
      if (ev.ctrlKey) {
        ev.preventDefault();
        ev.stopPropagation();
        (_a = ev.stopImmediatePropagation) == null ? void 0 : _a.call(ev);
        uiHelper.handleDecryptClick(this.app, this, ev, btn.dataset.secret || "");
        return;
      }
      ev.preventDefault();
      ev.stopPropagation();
      (_b = ev.stopImmediatePropagation) == null ? void 0 : _b.call(ev);
      setTimeout(() => uiHelper.openContextMenuAtEvent(this.app, this, ev, btn.dataset.secret || ""), 0);
    }, { capture: true });
  }
  findEncryptedBlockAtCursor(editor) {
    var _a, _b, _c, _d, _e;
    const cursor = editor.getCursor();
    const lineText = (_a = editor.getLine(cursor.line)) != null ? _a : "";
    const before = lineText.slice(0, cursor.ch);
    const after = lineText.slice(cursor.ch);
    const left = before.lastIndexOf("`");
    const right = after.indexOf("`");
    if (left >= 0 && right >= 0) {
      const content = lineText.slice(left + 1, cursor.ch + right);
      const trimmed = content.trimStart();
      if (trimmed.startsWith(ENCRYPTED_CODE_PREFIX + " ")) {
        return {
          from: { line: cursor.line, ch: left },
          to: { line: cursor.line, ch: cursor.ch + right + 1 }
        };
      }
    }
    const openRe = new RegExp("^```\\s*" + ENCRYPTED_CODE_PREFIX + "\\s*$", "i");
    const fenceRe = /^```+/;
    let openLine = -1;
    for (let i = cursor.line; i >= 0; i--) {
      const t = (_b = editor.getLine(i)) != null ? _b : "";
      if (fenceRe.test(t)) {
        if (openRe.test(t)) openLine = i;
        break;
      }
    }
    if (openLine >= 0) {
      const last = editor.lastLine();
      let closeLine = -1;
      for (let i = openLine + 1; i <= last; i++) {
        const t = (_c = editor.getLine(i)) != null ? _c : "";
        if (fenceRe.test(t)) {
          closeLine = i;
          break;
        }
      }
      if (closeLine > openLine) {
        return {
          from: { line: openLine, ch: 0 },
          to: { line: closeLine, ch: (_e = (_d = editor.getLine(closeLine)) == null ? void 0 : _d.length) != null ? _e : 0 }
        };
      }
    }
    return null;
  }
};

/* nosourcemap */