/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/

'use strict';

var obsidian = require('obsidian');

/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */

function __awaiter(thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
}

const DEFAULT_DATA = {
    intensity: 40,
};

class LimelightData {
    constructor(plugin) {
        this.plugin = plugin;
    }
    initialize() {
        return this.plugin.loadData().then((rawData) => {
            this.data = Object.assign({}, DEFAULT_DATA, rawData);
        });
    }
    getField(key) {
        this.validateInitialized();
        return this.data[key];
    }
    setField(key, value) {
        this.validateInitialized();
        this.data[key] = value;
        return this.plugin.saveData(this.data);
    }
    validateInitialized() {
        if (!this.data) {
            throw new Error('Plugin data is not initialized yet.');
        }
    }
}

function createIntensitySetting(container, data) {
    new obsidian.Setting(container)
        .setName('Spotlight intensity')
        .setDesc('Controls how dim the inactive panes are relative to the spotlighted pane.')
        .addSlider((slider) => {
        slider
            .setValue(data.getField('intensity')) // populate initial value from settings
            .onChange((value) => {
            // Write new value to settings
            data.setField('intensity', value);
            // Apply the new value to the UI
            applyIntensity(value);
        });
    });
}
function initializeIntensity(data) {
    // Apply the initial value to the UI
    applyIntensity(data.getField('intensity'));
}
function applyIntensity(intensity) {
    // Opacity ranges from 0.1 - 0.9, with MORE intense having a LOWER opacity
    // value (i.e. the other panes appear dimmer because the spotlight is so
    // bright).
    const opacity = 0.9 - 0.8 * (intensity / 100);
    document.body.style.setProperty('--limelight-opacity', opacity.toString());
}

class LimelightSettingTab extends obsidian.PluginSettingTab {
    constructor(app, plugin) {
        super(app, plugin);
        this.data = plugin.getData();
    }
    display() {
        const { containerEl } = this;
        containerEl.empty();
        createIntensitySetting(containerEl, this.data);
    }
}

class LimelightPlugin extends obsidian.Plugin {
    getData() {
        if (!this.data) {
            throw new Error('Plugin data has not been initialized yet.');
        }
        return this.data;
    }
    onload() {
        return __awaiter(this, void 0, void 0, function* () {
            this.data = new LimelightData(this);
            yield this.data.initialize();
            this.addSettingTab(new LimelightSettingTab(this.app, this));
            initializeIntensity(this.data);
        });
    }
}

module.exports = LimelightPlugin;


/* nosourcemap */